version: 0.2

env:
  variables:
    BUILD_BUCKET: "238160719262-builds"
    CLOUDFORMATION_BUCKET: "238160719262-cloudformation"
    DEPLOYMENT_ROLE: ""
    APP_CODE: ""
    ENVIRONMENT: "env"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install Git Client
      - apt-get update
      # - apt-get install --assume-yes git docker sudo
      # - pip3 uninstall --yes awscli
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install
      # - pip3 install aws-sam-cli
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Configuring AWS CLI
      - aws --version
      - aws configure set aws_access_key_id "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .AccessKeyId)"
      - aws configure set aws_secret_access_key "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .SecretAccessKey)"
      - aws configure set aws_session_token "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .Token)"
      - aws configure set profile.deployrole.region $AWS_REGION
      - aws configure set profile.deployrole.source_profile default
      - aws configure set profile.deployrole.role_arn $DEPLOYMENT_ROLE

      - sed -i '/^export AWS_PROFILE/d' ./config/.env.$ENVIRONMENT
      - chmod 777 ./config/.env.$ENVIRONMENT
      - echo reading in ./config/.env.$ENVIRONMENT
      - . ./config/.env.$ENVIRONMENT
      - echo Build set for environment $ENVIRONMENT
        
  build:
    commands:

      - echo validate awscli version
      - aws --version
      - sam --version

      # - echo prepare template parameters
      # - envsubst < template.params > .params.tmp
      # - cat .params.tmp | sed 's/\r//g' | sed 's/\n//g' > .params
      # - cat .params
  
      # - echo Building and Packaging Cloudformation template for environment $ENVIRONMENT
      # - |
      #   sam build \
      #     --region ${AWS_REGION} \
      #     ${SAM_DEBUG_OPTION}
      
      # - |
      #   sam package \
      #     --template-file .aws-sam/build/template.yaml \
      #     --output-template-file template-out.yaml \
      #     --s3-bucket ${CLOUDFORMATION_BUCKET} \
      #     --s3-prefix ${APP_CODE} \
      #     --region ${AWS_REGION} \
      #     ${SAM_DEBUG_OPTION}

      # - |
      #   sam deploy \
      #     --template-file template-out.yaml \
      #     --s3-bucket ${CLOUDFORMATION_BUCKET} \
      #     --s3-prefix ${APP_CODE} \
      #     --stack-name "${APP_CODE}-${ENVIRONMENT}-serverless-template" \
      #     --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
      #     --no-fail-on-empty-changeset \
      #     --profile deployrole \
      #     --region ${AWS_REGION} \
      #     ${SAM_DEBUG_OPTION} \
      #     --parameter-overrides $(cat .params)

artifacts:
  files:
    - buildspec-deploy.yaml
  discard-paths: yes
