version: 0.2

env:
  variables:
    BUILD_BUCKET: "238160719262-builds"
    CLOUDFORMATION_BUCKET: "238160719262-cloudformation"
    DEPLOYMENT_ROLE: ""
    BUILD_DOCKER_REPO: "238160719262.dkr.ecr.ap-southeast-2.amazonaws.com"
    APP_CODE: ""
    PIPELINE_NAME: ""
    REPOSITORY_NAME: ""
    BRANCH_NAME: ""
    COMMIT_ID: ""
    ENV_FILE: ".env"
    ENVIRONMENT: "env"
    PARAMS: ""
    SAM_DEBUG_OPTION:
  exported-variables:
    - PARAMS 

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install Git Client
      - apt-get update
      # - apt-get install --assume-yes git docker sudo
      # - pip3 uninstall --yes awscli
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Configuring AWS CLI
      - aws --version
      - aws configure set aws_access_key_id "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .AccessKeyId)"
      - aws configure set aws_secret_access_key "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .SecretAccessKey)"
      - aws configure set aws_session_token "$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r .Token)"
      - aws configure set profile.deployrole.region $AWS_REGION
      - aws configure set profile.deployrole.source_profile default
      - aws configure set profile.deployrole.role_arn $DEPLOYMENT_ROLE

      - sed -i '/^export AWS_PROFILE/d' ./config/.env.$ENVIRONMENT
      - chmod 777 ./config/.env.$ENVIRONMENT
      - echo reading in ./config/.env.$ENVIRONMENT
      - . ./config/.env.$ENVIRONMENT
      - echo Build set for environment $ENVIRONMENT
        
  build:
    commands:

      - echo validate awscli version
      - aws --version

artifacts:
  files:
    - buildspec-build.yaml
  discard-paths: yes
